version: "3.3"

services:
  
  server:
    build: .
    hostname: bacht-server
    container_name: bacht-server
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    links:
      - database
    depends_on:
      - database
    environment:
      SCALA_VERSION: 2.12.7
      DB_DRIVER: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    stdin_open: true
    tty: true

  database:
    image: mariadb:latest
    hostname: bacht-database
    container_name: bacht-database
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: unless-stopped

volumes:
  database:
