GET http://localhost:8000/api/noodles
Accept: text/plain
Cache-Control: no-cache

### ----------------------------------------------------------------- REGISTER

POST http://localhost:8000/api/auth/register
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "secret" }

### ------------------------------------------------------------ LOGIN SUCCESS

POST http://localhost:8000/api/auth/login
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "secret" }

> {%
    client.global.set("refresh_token", response.body.token);
%}

### ------------------------------------------------------------ LOGIN FAILURE

POST http://localhost:8000/api/auth/login
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "definitelynotthesecret" }

### ---------------------------------------------------------- REFRESH SUCCESS

POST http://localhost:8000/api/auth/refresh
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "{{refresh_token}}" }

> {%
    client.global.set("access_token", response.body.access);
    client.global.set("refresh_token", response.body.refresh);
%}

### ---------------------------------------------------------- REFRESH FAILURE

POST http://localhost:8000/api/auth/refresh
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "whatever" }

### ----------------------------------------------------------- LOGOUT SUCCESS

POST http://localhost:8000/api/auth/logout
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "{{refresh_token}}" }

### ----------------------------------------------------------- LOGOUT FAILURE

POST http://localhost:8000/api/auth/logout
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "whatever" }

### --------------------------------------------------------------- USERS LIST

GET http://localhost:8000/api/user
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{refresh_token}}
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- SPECIFIC USER

GET http://localhost:8000/api/user/self
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- UPDATE USER
PUT http://localhost:8000/api/user/
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

{"username" : "john","firstName": "johndoe","lastName" : "latourdoe","biopic"  : "qmdlkfjmlqdksfj"}

### ------------------------------------------------------------- DELETE USER

DELETE http://localhost:8000/api/user
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- SHAREAS LIST

GET http://localhost:8000/api/sharea
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### --------------------------------------------------------- USER SHAREAS LIST

GET http://localhost:8000/api/user/self/sharea
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ----------------------------------------------------------- SPECIFIC SHAREA

GET http://localhost:8000/api/sharea/1
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- CREATE SHAREA

POST http://localhost:8000/api/sharea
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

{ "name": "test", "description": "whatever" }

> {%
    client.global.set("last_sharea_id", response.body.id);
%}

### ------------------------------------------------------------- GET SHAREA

GET http://localhost:8000/api/sharea/{{last_sharea_id}}
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- GET SHAREA

GET http://localhost:8000/api/sharea
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- UPDATE SHAREA

PUT http://localhost:8000/api/sharea/{{last_sharea_id}}
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

{ "name": "ohmygod", "description": "it just changed name and description" }

> {%
    client.global.set("last_sharea_id", response.body.id);
%}

### ------------------------------------------------------------- DELETE SHAREA

DELETE http://localhost:8000/api/sharea/{{last_sharea_id}}
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- GET MEDIA KINDS

GET http://localhost:8000/api/media/kinds
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- CREATE MEDIA

POST http://localhost:8000/api/media
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

{ "name": "test", "kind": "text", "content":"qmsdfkjmlqskdjfmlksdjfmljk", "shareaId": {{last_sharea_id}} }

> {%
    client.global.set("last_media_id", response.body.id);
%}

### ------------------------------------------------------------- GET MEDIA

GET http://localhost:8000/api/media/{{last_media_id}}
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- UPDATE MEDIA

PUT http://localhost:8000/api/media/{{last_media_id}}
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

{ "name": "ohmygod", "kind": "text", "content": "qsjdkfm it just changed name and description" }

> {%
    client.global.set("last_media_id", response.body.id);
%}

### ------------------------------------------------------------- DELETE MEDIA

DELETE http://localhost:8000/api/media/{{last_media_id}}
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- LIKE A SHAREA

POST http://localhost:8000/api/sharea/{{last_sharea_id}}/sharealike
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- LIKE A MEDIA

POST http://localhost:8000/api/media/{{last_media_id}}/medialike
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}


### ------------------------------------------------------------- LIKE A USER

POST http://localhost:8000/api/user/2/userlike
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}

### ------------------------------------------------------------- GET USER

GET http://localhost:8000/api/user/2
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}



### ------------------------------------------------------------- USER JOINS SHAREA

POST http://localhost:8000/api/sharea/5/user
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}


### ------------------------------------------------------------- GET USERS COUNT IN SHAREA

GET http://localhost:8000/api/sharea/5/count_users
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}


### ------------------------------------------------------------- USER QUITS SHAREA

DELETE http://localhost:8000/api/sharea/5/user
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{access_token}}
